dna = "GGGTTTGCCCGAACGATACCAGTAGGGCGTAACGTATGTTGTAATGCTGCGACCCACAAAGGTCCACTTTCTCATGATTATTTCGTCAGCATTCATCCGTCTAGGCTTCTAACTGGGTCGGCATTCTCATGCCTGTGTCGTCCACGTGACTCTCAGCAAATATCGGTGTACGTTCTCAGGTGCCGATTAGCCTAGCTCAGGAATGCCTATAAGATCCGACATGGTTTCGGGATTGATAAAAACGATAAGTGCTAAAGCACGTAAACATGACGCCCTAAATCGTTCTCAAACTTGCTGCACCATTCTGATTGGCTTTGAACGTAGCGCCTCGATACGGAAGCGCCTGCCTGATCATGTTGTGACGTGCCACTGTGGCCTGCTAGGTCGACCGCCCCTGCTTATCGTCCACGGGCAAGGAGGCCGTACCCGGTAGACGGAGCCTGAACAGCTTTCCACACCACTCCCTGCCGAAGGCATCAAAGAACCACAAAATGCATTTCGACGCAAGGGGGTATCGGCATGCTGGGTTCGAGACGCCAGCTGCATGATCGAAGTAATTGGGAAACTTCGGCTGGCTCTAGGGATACCCGACCTAGCGGTGTATAACTGCGAGCTAGCCCGATCTTGCCCACGCAATACAAACCAGGCCGAAATCAGGATATCGTACTCCATTAGATAATTATATACGCCAACACTCTTACATGCACTAACGTGTGCCAAAGGAGTTGTCGCCCCACCGTAACACACCAGCCTGTTTTGGTCACTGTACTGGACCGCGTTCCGTCCGGATCCGCTGTCTAGTTCCGACGCAGCGACAC"
a = 0
t = 0
g = 0
c = 0
for nucleotide in dna:
    if nucleotide == "A":
        a += 1
    elif nucleotide == "T":
        t += 1
    elif nucleotide == "C":
        c += 1
    elif nucleotide == "G":
        g += 1
print("%s %s %s %s" % (a, c, g, t))